version: '3.3'

services:

  db:
    build: db
    image: zada04/words-db

  words:
    build: words
    image: zada04/words-app
    deploy:
      replicas: 5

  web:
    build: web
    image: zada04/words-web
    ports:
     - "8080:80"
